name: build and push

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # Specify your Java version
          distribution: 'temurin'

      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.16.0
        with:
          maven-version: '3.9.2'        

      - name: Build with Maven
        run: mvn clean install  

      - name: Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: target/*.jar        

      - name: Test Maven
        run: mvn test  

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact

      - name: List files
        run: ls -la

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIV_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
          
      - name: Copy files to EC2
        run: |
          scp -i ~/.ssh/id_rsa -r *.jar ubuntu@${{ secrets.EC2_HOST }}:~/*.jar
          
      - name: Cleanup SSH key
        if: always()
        run: rm -f ~/.ssh/id_rsa
    
