name: build and push

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # Specify your Java version
          distribution: 'temurin'

      - name: Setup Maven Action
        uses: s4u/setup-maven-action@latest
        with:
          maven-version: '3.9.2'        

      - name: Build with Maven
        run: mvn clean install  
