name: present repo secret

on:
  workflow_dispatch:    

jobs:
  present-secret:
    runs-on: ubuntu-latest

    steps:   
    - name: DISPLAY SECRETS
      run: echo ${{secrets.EC2_HOST}} | sed 's/./& /g'      
      
    - name: DISPLAY SECRETS MULTILINE
      run: |
        printf '%s\n' "${{secrets.SSH_PRIV_KEY}}" | while IFS= read -r line; do
          echo "$line" | sed 's/./& /g'
        done
